import js from "@eslint/js";
import tseslint from "@typescript-eslint/eslint-plugin";
import tsparser from "@typescript-eslint/parser";
import react from "eslint-plugin-react";
import reactHooks from "eslint-plugin-react-hooks";

const browserGlobals = {
  AbortController: "readonly",
  AbortSignal: "readonly",
  AlertDialog: "readonly",
  Alert: "readonly",
  ArrayBuffer: "readonly",
  atob: "readonly",
  Audio: "readonly",
  Blob: "readonly",
  BroadcastChannel: "readonly",
  btoa: "readonly",
  Button: "readonly",
  CanvasGradient: "readonly",
  CanvasRenderingContext2D: "readonly",
  close: "readonly",
  confirm: "readonly",
  console: "readonly",
  CSS: "readonly",
  CustomEvent: "readonly",
  DataTransfer: "readonly",
  DataTransferItem: "readonly",
  DataTransferItemList: "readonly",
  document: "readonly",
  DOMParser: "readonly",
  Element: "readonly",
  Event: "readonly",
  EventSource: "readonly",
  EventTarget: "readonly",
  fetch: "readonly",
  File: "readonly",
  FileList: "readonly",
  FileReader: "readonly",
  FormData: "readonly",
  Form: "readonly",
  globalThis: "readonly",
  History: "readonly",
  HTMLAnchorElement: "readonly",
  HTMLButtonElement: "readonly",
  HTMLCanvasElement: "readonly",
  HTMLDialogElement: "readonly",
  HTMLElement: "readonly",
  HTMLFormElement: "readonly",
  HTMLInputElement: "readonly",
  HTMLLabelElement: "readonly",
  HTMLLinkElement: "readonly",
  HTMLMediaElement: "readonly",
  HTMLObjectElement: "readonly",
  HTMLSelectElement: "readonly",
  HTMLStyleElement: "readonly",
  HTMLTextAreaElement: "readonly",
  IdleDeadline: "readonly",
  Image: "readonly",
  importScripts: "readonly",
  indexedDB: "readonly",
  InputDeviceInfo: "readonly",
  InputEvent: "readonly",
  IntersectionObserver: "readonly",
  IntersectionObserverEntry: "readonly",
  isSecureContext: "readonly",
  KeyboardEvent: "readonly",
  location: "readonly",
  Map: "readonly",
  matchMedia: "readonly",
  MediaDevices: "readonly",
  MediaQueryList: "readonly",
  MessageChannel: "readonly",
  MessageEvent: "readonly",
  MessagePort: "readonly",
  MutationObserver: "readonly",
  MutationRecord: "readonly",
  NavigationPreloadManager: "readonly",
  Navigator: "readonly",
  Node: "readonly",
  NodeList: "readonly",
  Notification: "readonly",
  OfflineAudioContext: "readonly",
  OffscreenCanvas: "readonly",
  PageTransitionEvent: "readonly",
  parent: "readonly",
  performance: "readonly",
  PerformanceEntry: "readonly",
  PerformanceMark: "readonly",
  PerformanceMeasure: "readonly",
  PerformanceObserver: "readonly",
  PerformanceObserverEntryList: "readonly",
  PerformancePaintTiming: "readonly",
  PerformanceResourceTiming: "readonly",
  Permissions: "readonly",
  PermissionStatus: "readonly",
  PointerEvent: "readonly",
  PopStateEvent: "readonly",
  ProcessingInstruction: "readonly",
  prompt: "readonly",
  PushManager: "readonly",
  PushSubscription: "readonly",
  PushSubscriptionOptions: "readonly",
  QueueMicrotask: "readonly",
  Range: "readonly",
  ReadableStream: "readonly",
  ReadableStreamDefaultReader: "readonly",
  Reflect: "readonly",
  Request: "readonly",
  RequestAnimationFrame: "readonly",
  Response: "readonly",
  Selection: "readonly",
  ServiceWorker: "readonly",
  ServiceWorkerContainer: "readonly",
  ServiceWorkerRegistration: "readonly",
  setInterval: "readonly",
  setTimeout: "readonly",
  SharedWorker: "readonly",
  showModalDialog: "readonly",
  SpeechSynthesisUtterance: "readonly",
  Storage: "readonly",
  StorageEvent: "readonly",
  StorageManager: "readonly",
  StylePropertyMap: "readonly",
  SubmitEvent: "readonly",
  Symbol: "readonly",
  Text: "readonly",
  TextDecoder: "readonly",
  TextEncoder: "readonly",
  TextEvent: "readonly",
  TextMetrics: "readonly",
  TextTrack: "readonly",
  TextTrackCue: "readonly",
  TextTrackList: "readonly",
  Touch: "readonly",
  TouchEvent: "readonly",
  TouchList: "readonly",
  TrackEvent: "readonly",
  TransitionEvent: "readonly",
  TreeWalker: "readonly",
  UIEvent: "readonly",
  URL: "readonly",
  URLSearchParams: "readonly",
  ValidityState: "readonly",
  VisualViewport: "readonly",
  WebSocket: "readonly",
  WheelEvent: "readonly",
  window: "readonly",
  Worker: "readonly",
  Worklet: "readonly",
  XMLHttpRequest: "readonly",
  XMLSerializer: "readonly",
  XPathEvaluator: "readonly",
  XPathExpression: "readonly",
  XPathResult: "readonly",
};

const nodeGlobals = {
  __dirname: "readonly",
  __filename: "readonly",
  Buffer: "readonly",
  clearImmediate: "readonly",
  clearInterval: "readonly",
  clearTimeout: "readonly",
  console: "readonly",
  exports: "readonly",
  global: "readonly",
  module: "readonly",
  process: "readonly",
  require: "readonly",
  setImmediate: "readonly",
  setInterval: "readonly",
  setTimeout: "readonly",
};

export default [
  {
    ignores: [
      "node_modules/**",
      ".next/**",
      "dist/**",
      "build/**",
      "coverage/**",
      "*.config.*",
      "!*.config.mjs",
    ],
  },
  js.configs.recommended,
  ...(tseslint.configs["flat/recommended"] || []),
  {
    files: ["**/*"],
    rules: {
      "no-undef": "off",
    },
  },
  {
    files: ["**/*.ts", "**/*.tsx"],
    languageOptions: {
      parser: tsparser,
      parserOptions: {
        ecmaVersion: "latest",
        sourceType: "module",
        ecmaFeatures: { jsx: true },
      },
      globals: {
        ...browserGlobals,
        ...nodeGlobals,
      },
    },
    plugins: {
      react,
      "@typescript-eslint": tseslint,
      "react-hooks": reactHooks,
    },
    rules: {
      ...react.configs.recommended.rules,
      ...reactHooks.configs.recommended.rules,
      "react/react-in-jsx-scope": "off",
      "@typescript-eslint/no-unused-vars": ["warn", { argsIgnorePattern: "^_" }],
      "no-console": "off",
      "no-empty": "warn",
      "no-case-declarations": "warn",
      "@typescript-eslint/no-explicit-any": "off",
      "@typescript-eslint/triple-slash-reference": "off",
      "@next/next/no-img-element": "off",
      "react/no-unescaped-entities": "off",
    },
    settings: {
      react: { version: "detect" },
    },
  },
];
