import OpenAI from "openai";
import { logStructured } from "../../lib/logger.js";

const OPENAI_API_KEY = process.env.OPENAI_API_KEY;

const client = OPENAI_API_KEY ? new OpenAI({
    apiKey: OPENAI_API_KEY,
}) : null;

/**
 * Generate diverse, realistic consumer prompt variants for evaluating brand visibility in LLMs.
 *
 * @param {string} brandName - The primary brand being tested.
 * @param {Array<string>} [competitors=[]] - Optional competitor names for comparative evaluation.
 * @param {string} [industry="banking"] - Industry context.
 * @returns {Array<{ id: string, category: string, prompt: string }>}
 */
export function generatePromptVariants(brandName, competitors = [], industry = "perbankan") {
    const cleanBrand = brandName?.trim() || "Bank Mandiri";
    const comp1 = competitors[0]?.trim() || "BCA";
    const comp2 = competitors[1]?.trim() || "Bank Danamon";

    return [
        {
            id: "reputation",
            category: "Reputasi & Kredibilitas",
            prompt: `Bagaimana reputasi, keandalan, dan rekam jejak ${cleanBrand} dalam industri ${industry} di Indonesia?`,
        },
        {
            id: "security",
            category: "Keamanan & Proteksi",
            prompt: `Apakah layanan transaksi digital dan aplikasi ${cleanBrand} aman digunakan dari risiko kejahatan siber dan kebocoran data nasabah?`,
        },
        {
            id: "comparison",
            category: "Rekomendasi & Komparasi",
            prompt: competitors.length > 0
                ? `Apa rekomendasi bank terbaik di Indonesia untuk tabungan dan transaksi harian antara ${cleanBrand} dibandingkan dengan ${comp1} dan ${comp2}?`
                : `Apa rekomendasi bank terbaik di Indonesia untuk kebutuhan tabungan, transfer gratis, dan kemudahan transaksi? Apakah ${cleanBrand} termasuk yang direkomendasikan?`,
        },
        {
            id: "digital_features",
            category: "Fitur & Inovasi Digital",
            prompt: `Bagaimana kualitas fitur mobile banking, kestabilan server transaksi, dan inovasi digital ${cleanBrand} saat ini?`,
        },
        {
            id: "customer_service",
            category: "Layanan Pelanggan",
            prompt: `Bagaimana tingkat kepuasan nasabah, kecepatan respons customer service, dan penanganan keluhan nasabah di ${cleanBrand}?`,
        },
    ];
}

/**
 * Check whether a term is present in text as a whole word or significant token.
 *
 * @param {string} text
 * @param {string} term
 * @returns {boolean}
 */
export function isTermMentioned(text, term) {
    if (!text || !term) return false;
    const lowerText = text.toLowerCase();
    const lowerTerm = term.toLowerCase().trim();

    // Check full term
    if (lowerText.includes(lowerTerm)) return true;

    // Check distinct sub-tokens if term is multi-word (e.g. "Bank Mandiri" -> "mandiri")
    const tokens = lowerTerm.split(/\s+/).filter(t => !["bank", "pt", "tbk", "central", "asia"].includes(t) && t.length > 3);
    for (const token of tokens) {
        const regex = new RegExp(`\\b${token}\\b`, "i");
        if (regex.test(lowerText)) return true;
    }

    return false;
}

/**
 * Analyze a single AI response for brand mention, sentiment, competitor positioning, and relevance.
 *
 * @param {string} responseText - Text generated by LLM.
 * @param {string} brandName - Primary brand under test.
 * @param {Array<string>} [competitors=[]] - Competitors to check.
 * @returns {object}
 */
export function analyzePromptResponse(responseText, brandName, competitors = []) {
    if (!responseText) {
        return {
            brandMentioned: false,
            sentiment: "neutral",
            brandTone: "neutral",
            competitorsMentioned: [],
            competitorTone: "neutral",
            relativePosition: "not_mentioned",
            relevanceScore: 0,
        };
    }

    const brandMentioned = isTermMentioned(responseText, brandName);

    // Analyze competitors
    const competitorsMentioned = (competitors || []).filter(comp => isTermMentioned(responseText, comp));

    // Sentiment Indicators
    const positiveWords = [
        "unggul", "terkemuka", "terbaik", "direkomendasikan", "rekomendasi", "aman", "terpercaya",
        "stabil", "inovatif", "mudah", "populer", "lengkap", "memuaskan", "andal", "leading",
        "top", "best", "recommended", "trusted", "secure", "reliable", "excellent", "seamless"
    ];
    const negativeWords = [
        "gangguan", "lemah", "keluhan", "masalah", "terkendala", "error", "lambat", "biaya tinggi",
        "kecewa", "risiko", "rentan", "down", "struggling", "complaint", "issue", "failure",
        "unreliable", "slow", "vulnerable", "fraud"
    ];

    const lower = responseText.toLowerCase();

    // Brand Sentiment
    let positiveHits = 0;
    let negativeHits = 0;

    for (const w of positiveWords) {
        if (lower.includes(w)) positiveHits++;
    }
    for (const w of negativeWords) {
        if (lower.includes(w)) negativeHits++;
    }

    let sentiment = "neutral";
    if (brandMentioned) {
        if (positiveHits > negativeHits + 1) {
            sentiment = "positive";
        } else if (negativeHits > positiveHits) {
            sentiment = "negative";
        } else {
            sentiment = "neutral";
        }
    }

    // Relative Position Assessment
    let relativePosition = "not_mentioned";
    if (brandMentioned) {
        const brandFirstIndex = lower.indexOf(brandName.toLowerCase());
        const isEarly = brandFirstIndex >= 0 && brandFirstIndex < 250;

        if (competitorsMentioned.length > 0) {
            const competitorFirstIndex = Math.min(...competitorsMentioned.map(c => {
                const idx = lower.indexOf(c.toLowerCase());
                return idx >= 0 ? idx : Infinity;
            }));

            if (sentiment === "positive" && (brandFirstIndex < competitorFirstIndex || isEarly)) {
                relativePosition = "leader";
            } else if (sentiment === "negative") {
                relativePosition = "lagging";
            } else {
                relativePosition = "competitive";
            }
        } else {
            relativePosition = sentiment === "positive" ? "top_tier" : "competitive";
        }
    }

    // Relevance Score (0.0 to 1.0)
    let relevanceScore = 0;
    if (brandMentioned) {
        relevanceScore = 0.5; // Base for being mentioned
        if (sentiment === "positive") relevanceScore += 0.3;
        else if (sentiment === "neutral") relevanceScore += 0.2;
        if (relativePosition === "leader" || relativePosition === "top_tier") relevanceScore += 0.2;
    }
    relevanceScore = Math.min(1.0, Math.round(relevanceScore * 100) / 100);

    return {
        brandMentioned,
        sentiment,
        brandTone: sentiment,
        competitorsMentioned,
        competitorTone: competitorsMentioned.length > 0 ? "neutral" : "neutral",
        relativePosition,
        relevanceScore,
    };
}

/**
 * Execute a single prompt query against OpenAI GPT-4o-mini.
 *
 * @param {string} promptText
 * @param {object} [options={}]
 * @returns {Promise<{ en: string, id: string, raw: string }>}
 */
export async function executeSimulatedPromptQuery(promptText, options = {}) {
    if (!OPENAI_API_KEY || !client) {
        logStructured("warn", "geo_engine_no_openai_key", { prompt: promptText });
        return {
            en: `[Simulated GPT-4o-mini] Objective response regarding the prompt: "${promptText}". Comprehensive overview with industry context and competitive insights.`,
            id: `[Simulasi GPT-4o-mini] Jawaban objektif mengenai pertanyaan: "${promptText}". Gambaran komprehensif dengan konteks industri dan analisis komparatif.`,
            raw: `Jawaban simulasi mengenai: ${promptText}`,
        };
    }

    const startedAt = Date.now();
    try {
        const completion = await client.chat.completions.create({
            model: "gpt-4o-mini",
            messages: [
                {
                    role: "system",
                    content: `Anda adalah asisten AI yang cerdas, objektif, dan netral. Pengguna menanyakan evaluasi atau rekomendasi terkait layanan perbankan dan finansial di Indonesia.
Berikan jawaban yang seimbang, realistis, dan berbasis fakta industri yang umum diketahui publik.
Jika relevan, sebutkan institusi atau regulator resmi (seperti OJK, Bank Indonesia) atau sumber informasi finansial terpercaya yang biasa menjadi rujukan.

Format respons WAJIB JSON dengan struktur:
{
  "id": "Jawaban lengkap dan natural dalam Bahasa Indonesia (150-250 kata)",
  "en": "Complete and natural answer in English (150-250 words)"
}`,
                },
                {
                    role: "user",
                    content: promptText,
                },
            ],
            temperature: 0.7,
            max_tokens: 1000,
            response_format: { type: "json_object" },
        });

        const rawContent = completion.choices[0]?.message?.content || "{}";
        let parsed = {};
        try {
            parsed = JSON.parse(rawContent);
        } catch {
            parsed = { id: rawContent, en: rawContent };
        }

        const idText = parsed.id || rawContent;
        const enText = parsed.en || idText;

        logStructured("info", "geo_prompt_query_succeeded", {
            promptLength: promptText.length,
            latencyMs: Date.now() - startedAt,
        });

        return {
            id: idText,
            en: enText,
            raw: idText,
        };
    } catch (error) {
        logStructured("error", "geo_prompt_query_failed", {
            error: error.message,
            prompt: promptText,
            latencyMs: Date.now() - startedAt,
        });
        throw error;
    }
}
